### ISSUE TITLE
Support "uniqueItems" in restrictions

### ISSUE THREAD

**Issue by seizans** [gumi/simple_schema#4]
Array の要素が unique であることを保証する "uniqueItems: true" を
SimpleSchema の制約で指定できると助かります。

**Comment by melpon** [comment]
[`SimpleSchema.Type.Unique`](https://github.com/gumi/simple_schema/blob/master/lib/simple_schema/type/unique.ex) を改造する方向で考えます。
今は `{SimpleSchema.Type.Unique, element_type: MyStruct, unique_key: :id}` みたいにして、配列の各構造体やマップの `:id` キーがユニークであるかどうかしかチェックできないですが、これを `{SimpleSchema.Type.Unique, element_type: MyStruct, unique_key: fn x -> x end}` みたいに関数も指定出来るようにしようかと思います。

**Comment by seizans** [comment]
希望を伝えそこねてたのですが、
こんな感じで書けるといいなと思っています。

```
  defmodule RequestSchema do
    import SimpleSchema, only: [defschema: 1]

    defschema(gift_ids: {[:integer], max_items: 10, unique_items: true})
  end
```

**Comment by melpon** [comment]
これのために組み込みのプロパティを追加するのはなーという気持ち…。

**Comment by seizans** [comment]
JsonSchema でバリデーション定義して ExJsonSchema 使ってた箇所を
全面的に SimpleSchema に機械的に書き換えてる途中だったんですけど、
uniqueItems が無くて詰まったとこだったんすよ...

**Comment by melpon** [comment]
ああなるほど、JSON Schema に uniqueItems っていうがあるんですね。知らなかった…。
じゃあむしろ指定できるようにするべきなので直します。

**Comment by seizans** [comment]
オッスお願いします！

**Comment by melpon** [comment]
simple_schema 1.1.5 をリリースしました。unique_items 制約が使えるようになっています。

**Comment by seizans** [comment]
❤️ ❤️ ❤️

**Comment by melpon** [comment]
Joseっぽさ…。
多分動くので閉じます。問題があれば reopen で。

**Comment by seizans** [comment]
期待通り動きました！
